import '../style/globals.css';
import type { Metadata } from 'next';
import { SFPRO } from '../assets/fonts/SFPRO';
import DarkModeProvider from '@/providers/DarkModeProvider';
import ThemeSwitcher from '@/components/atoms/ThemeSwitcher';

const sfpro = SFPRO;

export const metadata: Metadata = {
  title: 'Rasmus Elmersson',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={sfpro.className}>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
