import '../style/globals.css';
import type { Metadata } from 'next';
import { SFPRO } from '../assets/fonts/SFPRO';

const sfpro = SFPRO;

export const metadata: Metadata = {
  title: 'Rasmus Elmersson',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sfpro.className}>{children}</body>
    </html>
  );
}
